spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.example.gateway.model