spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
  mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.example.gateway.model